version: "3"
services:
  nginx:
    build: .
    ports:
      - "4545:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: /bin/bash -c "nginx -g 'daemon off;' & while :; do sleep 1; nginx -s reload; done"
